### PR TITLE
Add support for selector list

### PR DESCRIPTION
**Pull request by Lyokovic**
Hi,

Here is the implementation of #15, thanks for your advice!
I was not sure if I should split the `select` function, it did not looked weird to me to leave it like that.

I quickly tested it with a simple selector and with a selector list and it seems to work as (I) expected.

### CODE REVIEW

**Comment by Lyokovic** [comment]
Hah, maybe running the tests could help... Back to work :p

**Comment by aantron** [comment]
Yes, thank you :)

I would recommend also adding new tests for the new functionality.

**Comment by aantron** [comment]
@Lyokovic, it turns out some of the test failures were caused by an upstream change. I've adjusted to that in `master` (see d51e1c300484d0cb0ceab4d5859ecea056657b61). After rebasing on `master`, there are still some failures, that look related to the new code, but the test results are much less noisy.

**Comment by Lyokovic** [comment]
I just pushed a fix of a quite obvious mistake. But there is still one more failure with my branch, I do not get what is wrong :/

I'll try to add some tests later.

**Comment by aantron** [comment]
No problem, take your time. And let me know if you would like any form of assistance :)

**Comment by aantron** [comment]
Closing this PR as stale.

**Pull request closed without merging**
